USE Library;

INSERT INTO library_data (library_id, book_id, book_count) VALUES ('Bib1', 'bk1', 3);
INSERT INTO library_data (library_id, book_id, book_count) VALUES ('Bib1', 'bk2', 4);
INSERT INTO library_data (library_id, book_id, book_count) VALUES ('Bib1', 'bk3', 2);
INSERT INTO library_data (library_id, book_id, book_count) VALUES ('Bib2', 'bk1', 3);
INSERT INTO library_data (library_id, book_id, book_count) VALUES ('Bib2', 'bk3', 2);
