USE Library;

INSERT INTO library_data (library_name, library_location, book_name, author, book_count) VALUES ('Biblioteka1', 'Poznań', 'Władca Pierścieni', 'J.R.R. Tolkien', 3);
INSERT INTO library_data (library_name, library_location, book_name, author, book_count) VALUES ('Biblioteka1', 'Poznań', 'Diuna', 'Frank Herbert', 1);
INSERT INTO library_data (library_name, library_location, book_name, author, book_count) VALUES ('Biblioteka1', 'Poznań', 'Wojna i pokój', 'Lew Tołstoj', 2);
INSERT INTO library_data (library_name, library_location, book_name, author, book_count) VALUES ('Biblioteka2', 'Warszawa', 'O jeden most za daleko', 'Cornelius Ryan', 4);
INSERT INTO library_data (library_name, library_location, book_name, author, book_count) VALUES ('Biblioteka2', 'Warszawa', 'Folwark zwierzęcy', 'George Orwell', 3);
